int valPot;
int pinLED=8;
int pinVERTE=9;
int bouton=7;
int button=0;
//variable du choix du mot
long numeromot;
//liste des mots
const char *mots[]={
"shell", 
"halls", 
"slick", 
"trick", 
"boxes", 
"leaks", 
"strobe", 
"bistro", 
"flick", 
"bombs", 
"break", 
"brick", 
"steak", 
"sting", 
"vector", 
"beats", 
};
int TempsAttente;

void setup() {
  // initialisation:
  Serial.begin(9600);
  //lumiere rouge
  pinMode(pinLED,OUTPUT);
  digitalWrite(pinLED,LOW);
  //lumiere verte
  pinMode(pinVERTE,OUTPUT);
  digitalWrite(pinVERTE, LOW);
  //bouton
  pinMode(bouton,INPUT);
  //choix du mot au hasard
  numeromot = (random(sizeof(mots)/sizeof(char*)));
  //renvoi du mot pour vérification
  Serial.println(mots[numeromot]);
}

void loop() {
  //lancement du programme
  button=digitalRead(bouton);
  LightMorse();
  
}

void success() {
  // en cas de succès, on appelle cette fonction qui va terminer la fonction
  digitalWrite(pinVERTE, HIGH);
}

void PotentiometerReader(int TempsAttente) {
  // lecture du potentiomètre en boucle, durant TempsAttente millisecondes:
  int Ntemps=0;
  while (Ntemps<TempsAttente){
    Ntemps=Ntemps+1;
    delay(1);
    //lecture du potentiomètre
    int valPot=analogRead(A0);
    //envoi de l'information sur l'ordinateur pour vérification
    Serial.println(valPot);
    //lecture du bouton
    if (button==HIGH){
      if (mots[numeromot]=="shell"){
        if (0<valPot<5){
          success();
        }
        else{
          continue;
        }
      }
      if (mots[numeromot]=="halls"){
        if (0<valPot<5){
          success();
        }
        else{
          continue;
        }
      }
      if (mots[numeromot]=="slick"){
        if (0<valPot<5){
          success();
        }
        else{
          continue;
        }
      }
      if (mots[numeromot]=="trick"){
        if (0<valPot<5){
          success();
        }
        else{
          continue;
        }
      }
      if (mots[numeromot]=="boxes"){
        if (0<valPot<5){
          success();
        }
        else{
          continue;
        }
      }
      if (mots[numeromot]=="leaks"){
        if (0<valPot<5){
          success();
        }
        else{
          continue;
        }
      }
      if (mots[numeromot]=="strobe"){
        if (0<valPot<5){
          success();
        }
        else{
          continue;
        }
      }
      if (mots[numeromot]=="bistro"){
        if (0<valPot<5){
          success();
        }
        else{
          continue;
        }
      }
      if (mots[numeromot]=="flick"){
        if (0<valPot<5){
          success();
        }
        else{
          continue;
        }
      }
      if (mots[numeromot]=="bombs"){
        if (0<valPot<5){
          success();
        }
        else{
          continue;
        }
      }
      if (mots[numeromot]=="break"){
        if (0<valPot<5){
          success();
        }
        else{
          continue;
        }
      }
      if (mots[numeromot]=="brick"){
        if (0<valPot<5){
          success();
        }
        else{
          continue;
        }
      }
      if (mots[numeromot]=="steak"){
        if (0<valPot<5){
          success();
        }
        else{
          continue;
        }
      }
      if (mots[numeromot]=="sting"){
        if (0<valPot<5){
          success();
        }
        else{
          continue;
        }
      }
      if (mots[numeromot]=="vector"){
        if (0<valPot<5){
          success();
        }
        else{
          continue;
        }
      }
      if (mots[numeromot]=="beats"){
        if (0<valPot<5){
          success();
        }
        else{
          continue;
        }
      }
    }
    else{
      continue
    }
  }
}

void LightMorse(void) {
  //fonction allumant les diodes et appelant la fonction de base
  if (mots[numeromot]=="shell"){
    //s
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);;
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(600);
    //h
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(600);
  //e
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(600);
  //l
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(600);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(600);
  //l
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(600);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(2000);
    }
    if (mots[numeromot]=="halls"){
      //h
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(600);
//a
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(600);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(600);
//l
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(600);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(600);
    //l
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(600);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(600);
    //s
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(2000);
    }
    if (mots[numeromot]=="slick"){
      //s
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(600);
      //l
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(600);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(600);
      //i
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(600);
      //c
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(600);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(600);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(600);
      //k
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(600);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(600);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(2000);
    }
    if (mots[numeromot]=="trick"){
      //t
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(600);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(600);
      //r
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(600);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(600);
      //i
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(600);
      //c
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(600);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(600);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(600);
      //k
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(600);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(600);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(2000);
    }
    if (mots[numeromot]=="boxes"){
      //b
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(600);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(600);
      //o
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(600);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(600);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(600);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(600);
      //x
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(600);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(600);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(600);
      //e
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(600);
      //s
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(2000);
    }
    if (mots[numeromot]=="leaks"){
      //l
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(600);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(600);
      //e
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(600);
      //a
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(600);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(600);
      //k
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(600);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(600);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(600);
      //s
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(2000);
    }
    if (mots[numeromot]=="strobe"){
      //s
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(600);
      //t
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(600);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(600);
      //r
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(600);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(600);
      //o
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(600);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(600);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(600);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(600);
      //b
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(600);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(600);
      //e
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(2000);
    }
    if (mots[numeromot]=="bistro"){
      //b
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(600);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(600);
      //i
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(600);
      //s
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(600);
      //t
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(600);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(600);
      //r
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(600);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(600);
      //o
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(600);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(600);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(600);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(2000);
    }
    if (mots[numeromot]=="flick"){
      //f
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(600);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(600);
      //l
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(600);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(600);
      //i
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(600);
      //c
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(600);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(600);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(600);
      //k
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(600);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(600);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(2000);
    }
    if (mots[numeromot]=="bombs"){
      //b
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(600);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(600);
      //o
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(600);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(600);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(600);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(600);
      //m
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(600);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(600);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(600);
      //b
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(600);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(600);
      //s
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(2000);
    }
    if (mots[numeromot]=="break"){
      //b
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(600);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(600);
      //r
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(600);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(600);
      //e
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(600);
      //a
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(600);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(600);
      //k
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(600);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(600);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(2000);
    }
    if (mots[numeromot]=="brick"){
            //b
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(600);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(600);
      //r
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(600);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(600);
      //i
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(600);
      //c
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(600);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(600);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(600);
      //k
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(600);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(600);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(2000);
    }
    if (mots[numeromot]=="steak"){
      //s
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(600);
      //t
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(600);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(600);
      //e
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(600);
      //a
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(600);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(600);
      //k
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(600);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(600);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(2000);
    }
    if (mots[numeromot]=="sting"){
      //s
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(600);
      //t
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(600);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(600);
      //i
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(600);
      //n
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(600);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(600);
      //g
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(600);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(600);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(2000);
    }
    if (mots[numeromot]=="vector"){
      //v
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(600);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(600);
      //e
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(600);
      //c
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(600);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(600);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(600);
      //t
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(600);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(600);
      //o
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(600);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(600);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(600);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(600);
      //r
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(600);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(2000);
    }
    if (mots[numeromot]=="beats"){
      //b
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(600);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(600);
      //e
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(600);
      //a
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(600);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(600);
      //t
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(600);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(600);
      //s
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(200);
      digitalWrite(pinLED,HIGH);
      PotentiometerReader(200);
      digitalWrite(pinLED,LOW);
      PotentiometerReader(2000);
    }
  }

